/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intents;

import DataAcces.DataAcces;
import DataAcces.Intent;
import java.awt.BorderLayout;
import java.awt.List;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import main.MainFrame;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 * Classe Intents és una finestra GUI que permet revisar intents pendents,
 * reproduir vídeos associats, i tornar a la finestra principal.
 * 
 * Funcionalitats:
 * - Carrega una llista d'intents pendents.
 * - Reprodueix, pausa i reprèn vídeos.
 * - Canvia entre la finestra actual i la finestra principal.
 * 
 * @autor Maqrok
 */
public class Intents extends javax.swing.JFrame {

    // Declaració de variables
    private EmbeddedMediaPlayerComponent mediaPlayer; // Component per reproduir vídeos
    JFileChooser fileChooser = new JFileChooser(); // Per seleccionar fitxers
    private DataAcces da = new DataAcces(); // Accés a la base de dades
    private boolean isPlaying = false; // Indica si el vídeo està en reproducció
    
    /**
     * Constructor de la classe Intents
     * Configura la finestra, desactiva la redimensionabilitat, 
     * centra la finestra i inicialitza els components.
     */
    public Intents() {
        setResizable(false); // Evita que la finestra es pugui redimensionar
        setLocationRelativeTo(null); // Centra la finestra en la pantalla
        getContentPane().setLayout(null); // Disposició manual dels components
        initComponents();
        mediaPlayer = new EmbeddedMediaPlayerComponent(); // Inicialitza el reproductor de vídeo
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER); // Afegeix el reproductor al panell
        loadPendingIntents(); // Carrega intents pendents
    }
    
    /**
     * Mètode que carrega la llista d'intents pendents per revisar.
     * Afegeix cada intent a la llista gràfica lstVideos.
     */
    private void loadPendingIntents() {
        var getPendingAttempts = da.getPendingAttempts(); // Obté els intents pendents
        DefaultListModel<Intent> listModel = new DefaultListModel<>();

        // Afegeix cada intent a la llista amb el nom de l'exercici i el fitxer de vídeo
        for (Intent intent : getPendingAttempts) {
            listModel.addElement(intent);
        }

        lstVideos.setModel(listModel); // Configura el model per a la llista
        lstVideos.setSelectedIndex(0); // Selecciona el primer element
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstVideos = new javax.swing.JList<>();
        pnlVideoPlayer = new javax.swing.JPanel();
        btnPauseResumeVideo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstVideos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVideosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVideos);

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - xxx.mp4"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());

        btnPauseResumeVideo.setText("Pause");
        btnPauseResumeVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseResumeVideoActionPerformed(evt);
            }
        });

        jButton1.setText("Enrere");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPauseResumeVideo)
                            .addGap(172, 172, 172))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPauseResumeVideo)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauseResumeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseResumeVideoActionPerformed
        // TODO add your handling code here:
        if(isPlaying) {
            mediaPlayer.mediaPlayer().controls().pause(); // Pausa el vídeo
            isPlaying = false;
            btnPauseResumeVideo.setText("Resume"); // Canvia el text del botó a 'Resume'
        } else {
            mediaPlayer.mediaPlayer().controls().start(); // Reprèn el vídeo
            isPlaying = true;
            btnPauseResumeVideo.setText("Pause"); // Canvia el text del botó a 'Pause'
        }
    }//GEN-LAST:event_btnPauseResumeVideoActionPerformed

    private void lstVideosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVideosValueChanged
        if(evt.getValueIsAdjusting()) {
            return;
        }
        String videoPath = "src/main/resources/videos/videos/"; // Ruta del vídeo
        String videoFileAbsolutePath = videoPath + "\\" + lstVideos.getSelectedValue().getVideofile(); // Ruta completa
        File videoFile = new File(videoFileAbsolutePath); // Crea un fitxer amb la ruta del vídeo
        mediaPlayer.mediaPlayer().media().play(videoFile.getAbsolutePath()); // Reprodueix el vídeo
        mediaPlayer.mediaPlayer().controls().setRepeat(true); // Activa la repetició
        isPlaying = true;
    }//GEN-LAST:event_lstVideosValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Tanca la finestra actual
        MainFrame mainFrame = new MainFrame(); // Crea una nova instància de la finestra principal
        mainFrame.setVisible(true); // Mostra la finestra principal
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPauseResumeVideo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Intent> lstVideos;
    private javax.swing.JPanel pnlVideoPlayer;
    // End of variables declaration//GEN-END:variables
}
