/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Intents;

import DataAcces.DataAcces;
import DataAcces.Usuari;
import DataAcces.Intent;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import main.MainFrame;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 * Classe JFrame que mostra la informació dels usuaris i permet la selecció i reproducció
 * dels intents de vídeo associats a cada usuari. Inclou un reproductor de vídeo i 
 * funcionalitats per pausar, reprendre i canviar de vídeo.
 * * @autor Maqrok
 */
public class Usuaris extends javax.swing.JFrame {

    
    private EmbeddedMediaPlayerComponent mediaPlayer; // Component de reproductor de vídeo utilitzant VLCJ
    JFileChooser fileChooser = new JFileChooser(); // Selector d’arxius per seleccionar vídeos (no implementat aquí)
    private DataAcces da = new DataAcces(); // Objecte d'accés a dades per a operacions amb la base de dades
    private boolean isPlaying = false; // Estat de reproducció del vídeo

    /**
     * Constructor: Inicialitza els components de la interfície i carrega la llista d'usuaris.
     */
    public Usuaris() {
        setResizable(false); // Finestra no redimensionable
        setLocationRelativeTo(null); // Centrar la finestra a la pantalla
        getContentPane().setLayout(null); // Sense gestor de disseny per posicionament personalitzat
        initComponents(); // Inicialitza els components de Swing
        mediaPlayer = new EmbeddedMediaPlayerComponent(); // Inicialitza el component del reproductor de vídeo
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER); // Afegeix el reproductor al panell de vídeo
        loadUsers(); // Carrega la llista d'usuaris
        addTableSelectionListener(); // Afegeix el listener per gestionar la selecció de la taula
    
    }
    
    // Mètode per carregar usuaris en la llista
    private void loadUsers() {
        ArrayList<Usuari> users = da.getAllUsers(); // Obté la llista d'usuaris de la base de dades
        DefaultListModel<Usuari> listModel = new DefaultListModel<>(); // Model per a la llista d'usuaris

        // Afegeix cada usuari al model de la llista
        for (Usuari user : users) {
            listModel.addElement(user);
        }

        lstUsuaris.setModel(listModel); // Mostra els usuaris a lstUsuaris
        lstUsuaris.setSelectedIndex(0); // Selecciona el primer usuari per defecte
    }


    private void loadUserAttempts(Usuari selectedUser) {
        ArrayList<Intent> attempts = da.getAllAttemptsForUser(selectedUser.getId()); // Obté els intents

        SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); // Format per a la data
        DefaultTableModel tableModel = new DefaultTableModel(new Object[]{"ID", "Nom Exercici", "TimestampInici"}, 0);

        // Afegeix cada intent a la taula
        for (Intent intent : attempts) {
            String formattedDate = dateFormatter.format(intent.getTimestampInici()); 
            tableModel.addRow(new Object[]{intent.getId(), intent.getExerciseName(), formattedDate});
        }

        jTable1.setModel(tableModel); // Configura el model de la taula amb els intents

        // Carrega automàticament el primer intent si està disponible
        if (!attempts.isEmpty()) {
            String videoFile = attempts.get(0).getVideofile();
            loadVideo(videoFile);
            jTable1.setRowSelectionInterval(0, 0); // Selecciona la primera fila de la taula
        }
    }


    
    // Mètode per carregar i reproduir un vídeo
    private void loadVideo(String videoFileName) {
        String videoPath = "src/main/resources/videos/videos/"; // Ruta als vídeos
        String videoFileAbsolutePath = videoPath + videoFileName;
        mediaPlayer.mediaPlayer().media().play(videoFileAbsolutePath); // Reprodueix el fitxer de vídeo
        mediaPlayer.mediaPlayer().controls().setRepeat(true); // Reprodueix en bucle
        isPlaying = true;
    }
    
    // Esdeveniment per seleccionar un usuari i carregar els seus intents
    private void lstUsuarisValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            Usuari selectedUser = lstUsuaris.getSelectedValue();
            if (selectedUser != null) {
                loadUserAttempts(selectedUser); // Carregar intents de l'usuari seleccionat
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVideoPlayer = new javax.swing.JPanel();
        btnPauseResumeVideo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuaris = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - xxx.mp4"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());

        btnPauseResumeVideo.setText("Pause");
        btnPauseResumeVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseResumeVideoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstUsuaris);
        lstUsuaris.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsuarisValueChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Intent", "Nom exercici", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Enrere");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPauseResumeVideo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(btnPauseResumeVideo))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(72, 72, 72))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauseResumeVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseResumeVideoActionPerformed
        // TODO add your handling code here:
        
        if(isPlaying)
        {
            mediaPlayer.mediaPlayer().controls().pause();
            isPlaying = false;
            btnPauseResumeVideo.setText("Resume");
        }
        else 
        {
          mediaPlayer.mediaPlayer().controls().start();
          isPlaying = true;
          btnPauseResumeVideo.setText("Pause");
        }
    }//GEN-LAST:event_btnPauseResumeVideoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addTableSelectionListener() {
        jTable1.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    int selectedRow = jTable1.getSelectedRow();
                    if (selectedRow >= 0) {
                        // Obtener el ID del intento desde la tabla (columna 0)
                        int attemptId = (Integer) jTable1.getValueAt(selectedRow, 0);  // Obtenemos el ID del intento

                        // Recuperamos el intento completo a partir de su ID
                        Intent selectedIntent = da.getAttemptById(attemptId);  // Método que debería devolver un único intento

                        // Si el intento es válido, cargar el video correspondiente
                        if (selectedIntent != null) {
                            String videoFile = selectedIntent.getVideofile();  // Obtener el nombre del archivo de video
                            loadVideo(videoFile);  // Cargar el video en el reproductor
                        }
                    }
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuaris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPauseResumeVideo;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<Usuari> lstUsuaris;
    private javax.swing.JPanel pnlVideoPlayer;
    // End of variables declaration//GEN-END:variables
}
